[package]
name = "beans_interpreter"
version = "0.1.0"
authors = ["crax <gsolimeno97@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beans_lang = {path = "beans_lang"}
structopt = "0.3.1"