[package]
name = "beans_lang"
version = "0.1.0"
authors = ["crax <gsolimeno97@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"